export type MTGFormat = 
| "Standard"
| "Modern"
| "Pioneer"
| "Legacy"
| "Vintage"
| "Block Constructed"
| "Alchemy"
| "Historic"
| "Booster Draft"
| "Sealed Deck"
| "Cube Draft"
| "Commander"
| "Brawl"
| "Oathbreaker"
| "Pauper"
| "Tiny Leaders"
| "Two-Headed Giant"
| "Planechase"
| "Archenemy"
| "Tribal Wars"
| "Gladiator"
| "Historic Brawl"
| "Kitchen Table";
